# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
 platform :ios, '10.0'

target 'KKLibraryDemo_Pod' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # Pods for KKLibraryDemo_Pod
  
  use_frameworks!

  pod 'KeKeLibrary', '~> 0.1.27'


end
