
platform :ios, ’8.0’

inhibit_all_warnings!

use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'


target 'KeKeLibrary' do
    pod 'AFNetworking'
    pod 'FMDB'
   #pod 'PinYin4Objc'
end
